<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\AdminController:changepassword' => function () {
    return ($this->privates['service_locator.G66x7_2'] ?? $this->load('getServiceLocator_G66x72Service.php'));
}, 'App\\Controller\\MailController:recoverpassword' => function () {
    return ($this->privates['service_locator.etQ32mf'] ?? $this->load('getServiceLocator_EtQ32mfService.php'));
}, 'App\\Controller\\MailController:welcomeuser' => function () {
    return ($this->privates['service_locator.etQ32mf'] ?? $this->load('getServiceLocator_EtQ32mfService.php'));
}, 'App\\Controller\\SecurityController:login' => function () {
    return ($this->privates['service_locator.KELS8pk'] ?? $this->load('getServiceLocator_KELS8pkService.php'));
}, 'App\\Controller\\AdminController::changepassword' => function () {
    return ($this->privates['service_locator.G66x7_2'] ?? $this->load('getServiceLocator_G66x72Service.php'));
}, 'App\\Controller\\MailController::recoverpassword' => function () {
    return ($this->privates['service_locator.etQ32mf'] ?? $this->load('getServiceLocator_EtQ32mfService.php'));
}, 'App\\Controller\\MailController::welcomeuser' => function () {
    return ($this->privates['service_locator.etQ32mf'] ?? $this->load('getServiceLocator_EtQ32mfService.php'));
}, 'App\\Controller\\SecurityController::login' => function () {
    return ($this->privates['service_locator.KELS8pk'] ?? $this->load('getServiceLocator_KELS8pkService.php'));
})));
